[build]
  base = "/"
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "server"
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"